---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireactions-server.fullname" . }}-config
  labels:
    {{- include "fireactions-server.labels" . | nindent 4 }}
data:
  config.yaml: |-
    listen-addr: 0.0.0.0:{{ .Values.service.port }}
    data-dir: {{ .Values.config.dataDir }}
    github:
      job-label-prefix: {{ .Values.config.github.jobLabelPrefix }}
    {{- if .Values.config.scheduler }}
    scheduler: {{ toYaml .Values.config.scheduler | nindent 6 }}
    {{- end }}
    default-flavor: {{ .Values.config.defaultFlavor }}
    flavors: {{ toYaml .Values.config.flavors | nindent 6 }}
    default-group: {{ .Values.config.defaultGroup }}
    groups: {{ toYaml .Values.config.groups | nindent 6 }}
    log-level: {{ .Values.config.logLevel }}
