{{- if eq .Values.kind "Deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fireactions-server.fullname" . }}
  labels:
    {{- include "fireactions-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fireactions-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fireactions-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.hostAliases }}
      hostAliases:
      {{- toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fireactions-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/fireactions", "server"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.config.github.webhookSecret }}
            - name: FIREACTIONS_GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-github-secret" (include "fireactions-server.fullname" .)) .Values.config.github.existingSecret }}
                  key: webhook-secret
            {{- end }}
            - name: FIREACTIONS_GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-github-secret" (include "fireactions-server.fullname" .)) .Values.config.github.existingSecret }}
                  key: app-id
            - name: FIREACTIONS_GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-github-secret" (include "fireactions-server.fullname" .)) .Values.config.github.existingSecret }}
                  key: app-private-key
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/fireactions/config.yaml
              subPath: config.yaml
            - name: data
              mountPath: {{ .Values.config.dataDir }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fireactions-server.fullname" . }}-config
        - name: data
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
