---
version: 2
updates:
- package-ecosystem: "docker"
  directories:
    - "*/**"
    - "/"
  labels:
    - "dependencies"
    - "docker"
  reviewers:
    - "hostinger/cloudops-team"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"

- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "deps"
