---
builds:
- id: fireactions
  main: ./cmd/fireactions
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -X github.com/hostinger/fireactions/version.Version={{ .Version }}
  - -X github.com/hostinger/fireactions/version.Date={{ .Date }}
  - -X github.com/hostinger/fireactions/version.Commit={{ .Commit }}
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  binary: fireactions

archives:
- id: fireactions
  builds:
  - fireactions
  name_template: fireactions-v{{ .Version }}-{{ .Os }}-{{ .Arch }}
  format: tar.gz
  files:
  - src: LICENSE
    dst: LICENSE
  - src: README.md
    dst: README.md
  - src: docs/configuration.md
    dst: CONFIGURATION.md

dockers:
- id: server
  dockerfile: Dockerfile
  image_templates:
  - ghcr.io/hostinger/fireactions:{{ .Version }}
  - ghcr.io/hostinger/fireactions:latest
  extra_files:
    - "./"

release:
  mode: keep-existing

changelog:
  skip: true
