---
before:
  hooks:
  - go mod tidy

builds:
- id: fireactions
  main: .
  env:
  - CGO_ENABLED=0
  ldflags:
  - -X github.com/hostinger/fireactions/internal/buildinfo.Version={{ .Version }}
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  binary: fireactions

archives:
- id: fireactions
  builds:
  - fireactions
  name_template: fireactions-{{ .Version }}-{{ .Os }}-{{ .Arch }}
  format: tar.gz

dockers:
- id: server
  dockerfile: Dockerfile
  image_templates:
  - ghcr.io/hostinger/fireactions:{{ .Version }}
  - ghcr.io/hostinger/fireactions:latest
  extra_files:
    - "./"

release:
  draft: true

changelog:
  sort: asc
