// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_GetRunnerState_FullMethodName   = "/fireactions.agent.v1.AgentService/GetRunnerState"
	AgentService_GetRunnerVersion_FullMethodName = "/fireactions.agent.v1.AgentService/GetRunnerVersion"
	AgentService_GetLogs_FullMethodName          = "/fireactions.agent.v1.AgentService/GetLogs"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService provides status reporting for the GitHub Actions agent running in a VM.
type AgentServiceClient interface {
	// GetRunnerState retrieves the current state of the GitHub Actions runner.
	GetRunnerState(ctx context.Context, in *GetRunnerStateRequest, opts ...grpc.CallOption) (*GetRunnerStateResponse, error)
	// GetRunnerVersion retrieves the agent version.
	GetRunnerVersion(ctx context.Context, in *GetRunnerVersionRequest, opts ...grpc.CallOption) (*GetRunnerVersionResponse, error)
	// GetLogs streams logs from the agent service (server-side streaming).
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetLogsResponse], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) GetRunnerState(ctx context.Context, in *GetRunnerStateRequest, opts ...grpc.CallOption) (*GetRunnerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunnerStateResponse)
	err := c.cc.Invoke(ctx, AgentService_GetRunnerState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetRunnerVersion(ctx context.Context, in *GetRunnerVersionRequest, opts ...grpc.CallOption) (*GetRunnerVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunnerVersionResponse)
	err := c.cc.Invoke(ctx, AgentService_GetRunnerVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_GetLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetLogsRequest, GetLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GetLogsClient = grpc.ServerStreamingClient[GetLogsResponse]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService provides status reporting for the GitHub Actions agent running in a VM.
type AgentServiceServer interface {
	// GetRunnerState retrieves the current state of the GitHub Actions runner.
	GetRunnerState(context.Context, *GetRunnerStateRequest) (*GetRunnerStateResponse, error)
	// GetRunnerVersion retrieves the agent version.
	GetRunnerVersion(context.Context, *GetRunnerVersionRequest) (*GetRunnerVersionResponse, error)
	// GetLogs streams logs from the agent service (server-side streaming).
	GetLogs(*GetLogsRequest, grpc.ServerStreamingServer[GetLogsResponse]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) GetRunnerState(context.Context, *GetRunnerStateRequest) (*GetRunnerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunnerState not implemented")
}
func (UnimplementedAgentServiceServer) GetRunnerVersion(context.Context, *GetRunnerVersionRequest) (*GetRunnerVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunnerVersion not implemented")
}
func (UnimplementedAgentServiceServer) GetLogs(*GetLogsRequest, grpc.ServerStreamingServer[GetLogsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_GetRunnerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunnerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetRunnerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetRunnerState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetRunnerState(ctx, req.(*GetRunnerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetRunnerVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunnerVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetRunnerVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetRunnerVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetRunnerVersion(ctx, req.(*GetRunnerVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).GetLogs(m, &grpc.GenericServerStream[GetLogsRequest, GetLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GetLogsServer = grpc.ServerStreamingServer[GetLogsResponse]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fireactions.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRunnerState",
			Handler:    _AgentService_GetRunnerState_Handler,
		},
		{
			MethodName: "GetRunnerVersion",
			Handler:    _AgentService_GetRunnerVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLogs",
			Handler:       _AgentService_GetLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent/v1/agent.proto",
}
