// Code generated by MockGen. DO NOT EDIT.
// Source: commands/cmd.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	fireactions "github.com/hostinger/fireactions"
)

// Client is a mock of fireactionsClient interface.
type Client struct {
	ctrl     *gomock.Controller
	recorder *ClientMockRecorder
}

// ClientMockRecorder is the mock recorder for Client.
type ClientMockRecorder struct {
	mock *Client
}

// NewClient creates a new mock instance.
func NewClient(ctrl *gomock.Controller) *Client {
	mock := &Client{ctrl: ctrl}
	mock.recorder = &ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Client) EXPECT() *ClientMockRecorder {
	return m.recorder
}

// GetPool mocks base method.
func (m *Client) GetPool(ctx context.Context, name string) (*fireactions.Pool, *fireactions.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPool", ctx, name)
	ret0, _ := ret[0].(*fireactions.Pool)
	ret1, _ := ret[1].(*fireactions.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPool indicates an expected call of GetPool.
func (mr *ClientMockRecorder) GetPool(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPool", reflect.TypeOf((*Client)(nil).GetPool), ctx, name)
}

// ListMicroVMs mocks base method.
func (m *Client) ListMicroVMs(ctx context.Context, pool string) (*fireactions.MicroVMs, *fireactions.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMicroVMs", ctx, pool)
	ret0, _ := ret[0].(*fireactions.MicroVMs)
	ret1, _ := ret[1].(*fireactions.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMicroVMs indicates an expected call of ListMicroVMs.
func (mr *ClientMockRecorder) ListMicroVMs(ctx, pool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMicroVMs", reflect.TypeOf((*Client)(nil).ListMicroVMs), ctx, pool)
}

// ListPools mocks base method.
func (m *Client) ListPools(ctx context.Context, opts *fireactions.ListOptions) (fireactions.Pools, *fireactions.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPools", ctx, opts)
	ret0, _ := ret[0].(fireactions.Pools)
	ret1, _ := ret[1].(*fireactions.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPools indicates an expected call of ListPools.
func (mr *ClientMockRecorder) ListPools(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPools", reflect.TypeOf((*Client)(nil).ListPools), ctx, opts)
}

// PausePool mocks base method.
func (m *Client) PausePool(ctx context.Context, name string) (*fireactions.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PausePool", ctx, name)
	ret0, _ := ret[0].(*fireactions.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PausePool indicates an expected call of PausePool.
func (mr *ClientMockRecorder) PausePool(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PausePool", reflect.TypeOf((*Client)(nil).PausePool), ctx, name)
}

// Reload mocks base method.
func (m *Client) Reload(ctx context.Context) (*fireactions.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reload", ctx)
	ret0, _ := ret[0].(*fireactions.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reload indicates an expected call of Reload.
func (mr *ClientMockRecorder) Reload(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reload", reflect.TypeOf((*Client)(nil).Reload), ctx)
}

// ResumePool mocks base method.
func (m *Client) ResumePool(ctx context.Context, name string) (*fireactions.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumePool", ctx, name)
	ret0, _ := ret[0].(*fireactions.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumePool indicates an expected call of ResumePool.
func (mr *ClientMockRecorder) ResumePool(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumePool", reflect.TypeOf((*Client)(nil).ResumePool), ctx, name)
}

// ScalePool mocks base method.
func (m *Client) ScalePool(ctx context.Context, name string) (*fireactions.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScalePool", ctx, name)
	ret0, _ := ret[0].(*fireactions.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScalePool indicates an expected call of ScalePool.
func (mr *ClientMockRecorder) ScalePool(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScalePool", reflect.TypeOf((*Client)(nil).ScalePool), ctx, name)
}
