---
name: release-please

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: Run release-please
      uses: google-github-actions/release-please-action@v3
      with:
        package-name: fireactions
        release-type: go
        pull-request-title-pattern: 'chore${scope}: Release ${component} ${version}'
        skip-github-release: true
        token: ${{ secrets.ORG_GITHUB_TOKEN }}
